baseURL: https://kingchang.github.io/
languageCode: zh-tw
title: The Skynet devops blog
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-123456789-1

# Uncomment below to enable syntax highlighting
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle: pygments

taxonomies:
  tag: tags
  series: series
  category: categories

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Blog
    pre: edit
    url: /posts/
  #   weight: 2
  # - name: Development
  #   pre: edit
  #   url: /posts/develop/
  #   weight: 2
  # - name: Operator
  #   pre: edit
  #   url: /posts/operator/
  #   weight: 2
  # - name: Memo
  #   pre: edit
  #   url: /posts/memo/
  #   weight: 2
  - name: Tags
    pre: tag
    url: /tags/
    weight: 3
  - name: About
    pre: smile
    url: /about/
    weight: 4
  - name: RSS
    pre: rss
    url: /index.xml
    weight: 5

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Welcome to Skynet Devops Blog
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false

